name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

defaults:
  run:
    shell: bash

jobs:
  static-analysis:
    name: Static analysis

    runs-on: ubuntu-latest

    steps:
      - name: Install
        run: |
          sudo apt update
          sudo apt install cppcheck

      - name: Clone
        uses: actions/checkout@v3

      - name: cppcheck
        run: cppcheck --std=c++17 src/

  code-format:
    name: Code format check

    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: clang-format
        run: find src -type f -name \*.cc -o -name \*.h | xargs clang-format --dry-run --Werror

  android:
    name: Android

    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      - name: Cache cmake build
        uses: actions/cache@v3
        with:
          path: os/android/app/.cxx
          key: android-cmake-v1

      - name: Setup signing config
        if: env.KEYSTORE_FILE_BASE64 != '' && env.KEYSTORE_PROPERTIES_FILE_BASE64 != ''
        run: |
          cd os/android
          echo "$KEYSTORE_FILE_BASE64" | base64 --decode > debug.keystore
          echo "$KEYSTORE_PROPERTIES_FILE_BASE64" | base64 --decode > debug-keystore.properties
        env:
          KEYSTORE_FILE_BASE64: ${{ secrets.ANDROID_DEBUG_KEYSTORE_FILE_BASE64 }}
          KEYSTORE_PROPERTIES_FILE_BASE64: ${{ secrets.ANDROID_DEBUG_KEYSTORE_PROPERTIES_FILE_BASE64 }}

      - name: Build
        run: |
          cd os/android
          ./gradlew assembleDebug

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: fallout2-ce-debug.apk
          path: os/android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7
